name: Trigger auto deployment for tailcast-main

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tailcast-main-AutoDeployTrigger-790888dc-3d91-427c-9af9-4f6bd2cd9306.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TAILCASTMAIN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TAILCASTMAIN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TAILCASTMAIN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cr5x2wj2ymvayau.azurecr.io
          registryUsername: ${{ secrets.TAILCASTMAIN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TAILCASTMAIN_REGISTRY_PASSWORD }}
          containerAppName: tailcast-main
          resourceGroup: rg-sologid-tech-hub
          imageToBuild: cr5x2wj2ymvayau.azurecr.io/tailcast-main:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


